### PR TITLE
fix: events memory leak. Using new events implementation and take recorder out of EvictPod

### LINKED ISSUE #884: Memory consumption of the descheduler
Hey,

we had a memory leak reported internally. and this made us start an investigation into the descheduler memory consumption with various strategies with some scales of nodes and pods. I want to use this issue to both walk everyone through our findings and also report the memory leak itself.

The leak did not seem to appear in very small setups, or at least it was slow enough to be hard to reproduce, so I went to a bigger setup to get results faster:

### First scenario - LifecycleAndUtilization:

Number of nodes in control plane: 3
Number of worker nodes: 15
Cluster built using openshift-installer for aws with default instance types.

- Started the test with 500 pods
- Installed the kube-descheduler-operator from operatorhub
- Applied a KubeDescheduler resource with only LifecycleAndUtilization profile
- Started monitoring memory consumption in grafana
- RAM oscilates quite a bit, but does not accumulate
- goes from 16mb, 40mb, back to 20... and so on
- I bumped number of pods to 700
- Some pods get evicted by descheduler at some cycles, but memory seems to oscilate at the same range
- I bump to 1000, wait a bit, then to 1250 and to 1500 and memory seems to be always in the same range.

Here is the graph:

image

### Second scenario - AffinityAndTaints:

- Started with 500 pods
- Memory consumption around 20mb
- Bumped to 1000 pods
- Same consumption basically
- Threw a taint of NoSchedule in one of the nodes
- Memory consumption went up to 50mb
- Let it roll like that for a bit  to see
- Bumped pods to 1250, waited a bunch, then to 1500
- No change in memory with number of pods alone
- Introduced another taint in another node
- Around 93~95mb consumtion
- Third taint in
- Went to 114mb consumption

Here is the graph:

image

This is still not the memory leak that I am looking for, but it is interesting expected behavior for users to be aware.

### Third scenario - TopologyAndDuplicates:

- I already had some previous knowledge of suspicious behavior on this one and wait to 750 pods already
- Memory on 80mb consumption initially
- Increasing by itself, going to 100mb at 11:10 (graph below)
- Increased number of pods to 1000 to see if it would go up faster (11:20)
- Got to 500mb at 11:26 and with that, OOM killed (different timezone in grafana and terminal)

image

image

- At 11:36, back to 200 pods in the cluster to see if the curve goes slower
- It does
- I just wait for another OOM kill

image

### Forth scenario - TopologyAndDuplicates - Less nodes:

Here I changed my setup:

Number of nodes in control plane: 3

Number of worker nodes: 3

- Wanted to see if number of nodes would impact on something.
- So, initially with 200 pods, 12:54
- Memory oscilating around 25mb, 23mb, 27 mb...
- Left it like that for some minutes, nothing much happening
- Upped it to 500 pods
- Graph shows it going down (13:02), but not restarts are seen, probably something with the monitoring instrumentation pods
- Memory around 38 - 36, but no accumulation
- Upped it to 750 pods
- Again a drop in the graph that is not from a kill or restart, something with the monitoring pods
- Memory went up to ~104mb
- And started to clearly grow
- 123mb -> 140mb -> 175...
- Started to have some general pressure on multiple components... Also since it was a smaller cluster, api started to timeout and whatnot.

Here is the graph:

image

We confirm that this descheduler operator profile has the memory leak, and also, we confirm that it only actually is apparent with more than 750 pods in general. I don't think number of nodes impact that much here.

### Fifth scenario - RemoveDuplicates strategy:

- Back to 15 workers setup so I don't have to worry about it not being able to handle it
- Stopped using the operator and started deploying descheduler directly so I could enable single strategies
- Enabled RemoveDuplicates
- Already started with 750 pods
- Nothing much happening in memory (blue in graph)
- 14:57 bump to 1000 pods
- Same
- Realized descheduling-interval was bigger than I wanted, it was 5minutes or something like that
- Reduced to 7s, still 1000 pods (changes of color means new pod, because I applied with new arguments)
- 15:02 72 mb
- 15:04 144mb
- 15:07 Noticed things were maybe too fast [?]. Descheduler were evicting pods, they would get in ContainerCreating Status, and Descheduler would be evicting more pods before the previous ones would be Running still. So I assumed things were piggybacking on each other, and memory was going up fast.
- Increased to descheduling-interval 20s
- Still too fast
- 15:11 increased to 40s. Still too fast
- Then to 2m, which seemed fine. Gave pods a change to be running before a cycle comes around
- Every run it evics around 49~80 pods (since most come from the same deployment, bunch of duplicates in nodes)
- ~57:21 84mb, 15:25 105 mb
- Memory growing even with a good space between my evictions and these same pods being running again. I think we have a Leak here
- 15:33 135mb
- 15:34 1250 pods

Graph here:

image

### Sixth scenario - TopologySpreadConstrain strategy:

- Already with 1000 pods
- Starts growing wich makes me think we will see another leak
- It seems to stabilize and just oscilate
- 16:46 1250 pods
- 16:50 1500 pods
- 16:59 1750 pods
- Left it running for longer 

image

.

image

- Recreated with small refresh since this one is not actually evicting anything
- Not much change
- More pods makes it use more memory, so there is a limitation here, and around 10kpods I think we hit OOM kills from time to time, even though we don't have a leak here

Another graph: 

image

Wanted to create this issue already, before I would forget and would reach a point where I could not make sense of my notes. I will investigate the RemoveDuplicates leak specifically further next and circle back here.

### PR DESCRIPTION
**Pull request by knelasevero**
Fixes #884 

I was trying something around #887 but that did not do it. There I just mistakenly removed `StartRecordingToSink` which when reintroduced would cause the leak again. So you can just ignore that. (just mentioning to document attempts)

Shutting down eventBroadcaster seems to do the trick. If we look back to the [pprof top report for in use objects](https://github.com/kubernetes-sigs/descheduler/issues/884#issuecomment-1180547263) we see that we have something getting accumulated in k8s.io/apimachinery/pkg/watch.(*Broadcaster).Watch. I am guessing every time we call StartRecordingToSink that is when we start accumulating it.

Shutting down the eventBroadcaster right after we publish the event seems to stop this accumulation and it also seems to not affect the publication of the event itself (I kept monitoring some evicted pods in terminating state to be sure):

```
Events:
  Type    Reason          Age   From                     Message
  ----    ------          ----  ----                     -------
  Normal  Scheduled       2m    default-scheduler        Successfully assigned default/nginx-deployment-85d945584d-zvcps to ip-10-0-177-50.ec2.internal
  Normal  AddedInterface  116s  multus                   Add eth0 [10.130.2.231/23] from openshift-sdn
  Normal  Pulled          115s  kubelet                  Container image "k8s.gcr.io/pause:3.1" already present on machine
  Normal  Created         111s  kubelet                  Created container nginx
  Normal  Started         111s  kubelet                  Started container nginx
  Normal  Descheduled     29s   sigs.k8s.io.descheduler  pod evicted by sigs.k8s.io/descheduler
```

Here is new graph of memory consumption:

image

### CODE REVIEW

**Review by damemi — COMMENTED** [review]
/ok-to-test

File: pkg/descheduler/evictions/evictions.go [hunk 1]
```diff
@@ -171,6 +171,7 @@ func (pe *PodEvictor) EvictPod(ctx context.Context, pod *v1.Pod, opts EvictOptio
 		eventBroadcaster.StartRecordingToSink(&clientcorev1.EventSinkImpl{Interface: pe.client.CoreV1().Events(pod.Namespace)})
 		r := eventBroadcaster.NewRecorder(scheme.Scheme, v1.EventSource{Component: "sigs.k8s.io.descheduler"})
 		r.Event(pod, v1.EventTypeNormal, "Descheduled", fmt.Sprintf("pod evicted by sigs.k8s.io/descheduler%s", opts.Reason))
+		eventBroadcaster.Shutdown()
```
Comment (ingvagabund) [inline pkg/descheduler/evictions/evictions.go:174]: I wonder whether we actually broadcast the events properly. Checking the KS code [1]:
```
cc.EventBroadcaster.StartRecordingToSink(ctx.Done())
defer cc.EventBroadcaster.Shutdown()
```
and [2]:
```
// Prepare kube clients.
client, eventClient, err := createClients(kubeConfig)
if err != nil {
	return nil, err
}

c.EventBroadcaster = events.NewEventBroadcasterAdapter(eventClient)
```

`StartRecordingToSink` and `Shutdown` is invoked only once.

[1] https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L160-L161
[2] https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/options.go#L280-L286

Comment (damemi) [reply pkg/descheduler/evictions/evictions.go:174]: I would think the eventbroadcaster should be started at startup (followed by a defer), and then just passed everywhere it's used. I agree it seems weird we're starting and stopping it right here

Comment (ingvagabund) [reply pkg/descheduler/evictions/evictions.go:174]: From https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/events/interfaces.go#L42:
```
Eventf(regarding runtime.Object, related runtime.Object, eventtype, reason, action, note string, args ...interface{})
```

The descheduler would then invoke `eventBroadcaster.Eventf(...)`

Comment (ingvagabund) [reply pkg/descheduler/evictions/evictions.go:174]: Worth refactoring the code and moving the bits up in https://github.com/kubernetes-sigs/descheduler/blob/d5e66ab62e3683dfce663417ba46f957b5b29b59/pkg/descheduler/descheduler.go#L169. `EvictPod` should be really invoking only a single command to record an event.

Comment (knelasevero) [reply pkg/descheduler/evictions/evictions.go:174]: Looking at it now I see that we probably are dealing with events in a non optimal way here. I will have a proper look at what kube-scheduler is doing there and reproduce it here

Comment (ingvagabund) [reply pkg/descheduler/evictions/evictions.go:174]: @knelasevero much appreciate the time and effort in investigating the issue and figuring out where the leak is

File: kubernetes/base/rbac.yaml [hunk 2]
```diff
@@ -4,7 +4,7 @@ apiVersion: rbac.authorization.k8s.io/v1
 metadata:
   name: descheduler-cluster-role
 rules:
-- apiGroups: [""]
+- apiGroups: ["events.k8s.io"]
```
Comment (knelasevero) [inline kubernetes/base/rbac.yaml:7]: now that I am using client-go/tools/events, had to specify this apiGroup so our service account can create events

File: pkg/descheduler/evictions/evictions.go [hunk 3]
```diff
@@ -166,11 +170,11 @@ func (pe *PodEvictor) EvictPod(ctx context.Context, pod *v1.Pod, opts EvictOptio
...
 	} else {
 		klog.V(1).InfoS("Evicted pod", "pod", klog.KObj(pod), "reason", opts.Reason, "strategy", strategy, "node", pod.Spec.NodeName)
-		eventBroadcaster := record.NewBroadcaster()
-		eventBroadcaster.StartStructuredLogging(3)
-		eventBroadcaster.StartRecordingToSink(&clientcorev1.EventSinkImpl{Interface: pe.client.CoreV1().Events(pod.Namespace)})
-		r := eventBroadcaster.NewRecorder(scheme.Scheme, v1.EventSource{Component: "sigs.k8s.io.descheduler"})
-		r.Event(pod, v1.EventTypeNormal, "Descheduled", fmt.Sprintf("pod evicted by sigs.k8s.io/descheduler%s", opts.Reason))
+		reason := opts.Reason
+		if len(reason) == 0 {
+			reason = "NotSet"
```
Comment (knelasevero) [inline pkg/descheduler/evictions/evictions.go:175]: We are not setting Reasons yet, but if we try to emit events with Event and a empty Reason, it fails. I am leaving this here but we can remove when we start setting them in all strategies

File: pkg/descheduler/descheduler.go [hunk 4]
```diff
@@ -275,6 +277,10 @@ func RunDeschedulerStrategies(ctx context.Context, rs *options.DeschedulerServer
 		} else {
 			podEvictorClient = rs.Client
 		}
+		eventBroadcaster := events.NewEventBroadcasterAdapter(rs.EventClient)
+		eventBroadcaster.StartRecordingToSink(ctx.Done())
+		eventRecorder := eventBroadcaster.NewRecorder("sigs.k8s.io.descheduler")
```
Comment (knelasevero) [inline pkg/descheduler/descheduler.go:282]: I am creating the Recorder already here and passing it as another field in the PodEvictor struct, but if we look at how KS does it, it had a Recorder Factory with some other abstractions there: https://github.com/kubernetes/kubernetes/blob/8e14585d8700d9cf7861be66943f023d11d41075/cmd/kube-scheduler/app/server.go#L285

But I guess we should go that way only when we finish setting up the descheduler framework here

Comment (knelasevero) [reply pkg/descheduler/descheduler.go:282]: Hmm, looking at the failing e2e tests, maybe I need the factory

File: pkg/descheduler/evictions/evictions.go (hunk 3 above)
Comment (a7i) [reply pkg/descheduler/evictions/evictions.go:175]: we used to [set](https://github.com/kubernetes-sigs/descheduler/blob/v0.24.1/pkg/descheduler/evictions/evictions.go#L125) reason to strategy name if it wasn't set.

File: pkg/descheduler/strategies/node_affinity_test.go [hunk 5]
```diff
@@ -215,6 +216,11 @@ func TestRemovePodsViolatingNodeAffinity(t *testing.T) {
 			sharedInformerFactory.Start(ctx.Done())
 			sharedInformerFactory.WaitForCacheSync(ctx.Done())
 
+			eventBroadcaster := events.NewEventBroadcasterAdapter(fakeClient)
+			eventBroadcaster.StartRecordingToSink(ctx.Done())
+			eventRecorder := eventBroadcaster.NewRecorder("sigs.k8s.io.descheduler")
+			defer eventBroadcaster.Shutdown()
```
Comment (a7i) [inline pkg/descheduler/strategies/node_affinity_test.go:222]: can we move these to a common utility for the tests? Or perhaps `events.go` in [utils](https://github.com/kubernetes-sigs/descheduler/tree/master/pkg/utils) so descheduler and tests can call it.

File: pkg/descheduler/descheduler.go [hunk 6]
```diff
@@ -51,11 +52,12 @@ import (
 func Run(ctx context.Context, rs *options.DeschedulerServer) error {
 	metrics.Register()
 
-	rsclient, err := client.CreateClient(rs.KubeconfigFile)
+	rsclient, eventClient, err := createClients(rs.KubeconfigFile)
```
Comment (a7i) [inline pkg/descheduler/descheduler.go:55]: for my understanding, why do we need separate clients?

Comment (ingvagabund) [reply pkg/descheduler/descheduler.go:55]: The only difference between both clients is the userAgent. Which helps to separate e.g. descheduler audit logs from the events audit logs. Checking other components:
- [KCM has a single client](https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/cmd/kube-controller-manager/app/controllermanager.go#L184
)
- [kubelet has a single client](https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/cmd/kubelet/app/server.go#L450)
- [kube-proxy has both](https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/cmd/kube-proxy/app/server.go#L589)

Although in all the cases the event broadcaster is actually using only a single client for recording events:
KCM:
```go
eventBroadcaster := record.NewBroadcaster()
eventRecorder := eventBroadcaster.NewRecorder(clientgokubescheme.Scheme, v1.EventSource{Component: 
KubeControllerManagerUserAgent})
c.EventBroadcaster.StartStructuredLogging(0)
c.EventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: c.Client.CoreV1().Events("")})
defer c.EventBroadcaster.Shutdown()
```
kubelet:
```go
eventBroadcaster := record.NewBroadcaster()
kubeDeps.Recorder = eventBroadcaster.NewRecorder(legacyscheme.Scheme, v1.EventSource{Component: componentKubelet, Host: string(nodeName)})
eventBroadcaster.StartStructuredLogging(3)
eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: kubeDeps.EventClient.Events("")})
```
kube-proxy: it creates `eventClient` but still injects `client.EventsV1()` into the event broadcaster
```go
eventClient, err := clientset.NewForConfig(kubeConfig)
eventBroadcaster := events.NewBroadcaster(&events.EventSinkImpl{Interface: client.EventsV1()})
recorder := eventBroadcaster.NewRecorder(scheme.Scheme, "kube-proxy")
...
if s.Broadcaster != nil && s.EventClient != nil {
	stopCh := make(chan struct{})
	s.Broadcaster.StartRecordingToSink(stopCh)
}
...
```

Checking other places under `k8s.io/kubernetes/staging/src/k8s.io`:
```bash
$ grep -rn "\.StartRecordingToSink" --include "*.go" --exclude "*_test.go"
sample-controller/controller.go:101:	eventBroadcaster.StartRecordingToSink(&typedcorev1.EventSinkImpl{Interface: kubeclientset.CoreV1().Events("")})
client-go/tools/events/event_broadcaster.go:381:		e.eventsv1Broadcaster.StartRecordingToSink(stopCh)
client-go/tools/events/event_broadcaster.go:384:		e.coreBroadcaster.StartRecordingToSink(&typedv1core.EventSinkImpl{Interface: e.coreClient.Events("")})
legacy-cloud-providers/aws/aws.go:1423:	c.eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: c.kubeClient.CoreV1().Events("")})
legacy-cloud-providers/azure/azure.go:674:	az.eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: az.KubeClient.CoreV1().Events("")})
legacy-cloud-providers/gce/gce.go:655:	g.eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: g.client.CoreV1().Events("")})
cloud-provider/controllers/service/controller.go:114:	broadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: kubeClient.CoreV1().Events("")})
cloud-provider/controllers/node/node_controller.go:119:	eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: kubeClient.CoreV1().Events("")})
cloud-provider/controllers/route/route_controller.go:109:		rc.broadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: rc.kubeClient.CoreV1().Events("")})
cloud-provider/controllers/nodelifecycle/node_lifecycle_controller.go:78:	eventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: kubeClient.CoreV1().Events("")})
cloud-provider/app/controllermanager.go:148:	c.EventBroadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: c.Client.CoreV1().Events("")})
```

Looks like kube-scheduler is the only one creating a separate event client.

Comment (ingvagabund) [reply pkg/descheduler/descheduler.go:55]: @knelasevero I will leave it up to you to make the decision whether we use a single client or separate ones. I don't have any objections here.

File: pkg/descheduler/evictions/evictions.go (hunk 3 above)
Comment (knelasevero) [reply pkg/descheduler/evictions/evictions.go:175]: any reason we stopped doing that?

Comment (knelasevero) [reply pkg/descheduler/evictions/evictions.go]: Ok, did something similar now

File: pkg/descheduler/descheduler.go (hunk 6 above)
Comment (knelasevero) [reply pkg/descheduler/descheduler.go:56]: Since this project is closely related to KS in heart and soul, I would slightly prefer to keep it similar to what is being done in there. But also no strong preference from my side.

File: pkg/descheduler/descheduler.go (hunk 4 above)
Comment (knelasevero) [reply pkg/descheduler/descheduler.go]: @damemi @ingvagabund @a7i I tried a few things on my local to get e2e passing, but I am not sure why e2e tests are failing here :thinking:

I initially thought I was shutting broadcaster down prematurely in e2e tests. But it seems it wasnt it. Also tried having new recorders every-time, also did not help.

Any ideas here?

File: pkg/descheduler/strategies/node_affinity_test.go (hunk 5 above)
Comment (knelasevero) [reply pkg/descheduler/strategies/node_affinity_test.go]: Moved to events.go in utils. We still need to defer Shutdown in the upper level though, so I just created a function that returns both the broadcaster and the recorder.

File: test/e2e/e2e_test.go [hunk 7]
```diff
@@ -1424,6 +1429,11 @@ func initPodEvictorOrFail(t *testing.T, clientSet clientset.Interface, getPodsAs
 	if err != nil || len(evictionPolicyGroupVersion) == 0 {
 		t.Fatalf("Error creating eviction policy group: %v", err)
 	}
+
+	ctx := context.Background()
+	eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, clientSet)
+	defer eventBroadcaster.Shutdown()
```
Comment (ingvagabund) [inline test/e2e/e2e_test.go:1435]: `defer eventBroadcaster.Shutdown()` needs to be invoked outside of `initPodEvictorOrFail`

Comment (knelasevero) [reply test/e2e/e2e_test.go:1435]: I tried removing all defer shutdowns from e2e tests just to quickly to see if it would make e2e pass, but it didn't :(

I will make that change anyways :)

Comment (knelasevero) [reply test/e2e/e2e_test.go]: Hmm, maybe I imagined that, one of the e2e passed now

File: pkg/descheduler/evictions/evictions.go [hunk 8]
```diff
@@ -57,6 +55,8 @@ type PodEvictor struct {
 	nodepodCount               nodePodEvictedCount
 	namespacePodCount          namespacePodEvictCount
 	metricsEnabled             bool
+	eventBroadcaster           events.EventBroadcasterAdapter
```
Comment (ingvagabund) [inline pkg/descheduler/evictions/evictions.go:58]: `eventBroadcaster` is not used anywhere in the code, the parameter can be dropped

File: pkg/descheduler/strategies/duplicates_test.go [hunk 9]
```diff
@@ -313,6 +313,9 @@ func TestFindDuplicatePods(t *testing.T) {
 			sharedInformerFactory.Start(ctx.Done())
 			sharedInformerFactory.WaitForCacheSync(ctx.Done())
 
+			eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, fakeClient)
```
Comment (ingvagabund) [inline pkg/descheduler/strategies/duplicates_test.go:316]: Given the unit tests do not check the events recorded during testing the `eventRecorder` can be replaced by [NewFakeRecorder](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/events/fake.go#L41) which does not need any `eventBroadcaster.Shutdown()`.

File: test/e2e/e2e_duplicatepods_test.go [hunk 10]
```diff
@@ -138,6 +139,10 @@ func TestRemoveDuplicates(t *testing.T) {
 			if err != nil || len(evictionPolicyGroupVersion) == 0 {
 				t.Fatalf("Error creating eviction policy group %v", err)
 			}
+
+			eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, clientSet)
```
Comment (ingvagabund) [inline test/e2e/e2e_duplicatepods_test.go:143]: Given the e2e test does not check the events recorded during testing the `eventRecorder` can be replaced by [NewFakeRecorder](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/events/fake.go#L41) which does not need any `eventBroadcaster.Shutdown()`.

**Review by ingvagabund — CHANGES_REQUESTED** [review]

File: test/e2e/e2e_duplicatepods_test.go (hunk 10 above)
Comment (ingvagabund) [reply test/e2e/e2e_duplicatepods_test.go:143]: Benefit of the fake recorder is no go routine inside `Eventf`.

File: pkg/descheduler/descheduler.go [hunk 11]
```diff
@@ -330,6 +331,8 @@ func RunDeschedulerStrategies(ctx context.Context, rs *options.DeschedulerServer
 		} else {
 			podEvictorClient = rs.Client
 		}
+		eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, podEvictorClient)
```
Comment (ingvagabund) [inline pkg/descheduler/descheduler.go:334]: No need to create utils.GetRecorderAndBroadcaster in every cycle. The event recorder/broadcaster can be created only once and used throughout the entire run of the descheduler. E.g. https://github.com/kubernetes-sigs/descheduler/pull/891/commits/ca96f8387ab76c39eb26dbab091d928bdf6feaaf#diff-67816189b07b98460b57a10b41280403c53a4dfda42fdd8f54475812cb99f56eR291-R300

Comment (knelasevero) [reply pkg/descheduler/descheduler.go:334]: Nice!

**Comment by knelasevero** [comment]
All green :heavy_check_mark: :)

**Review by ingvagabund — CHANGES_REQUESTED** [review]
There are still few places in unit tests that have:
```
eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, fakeClient)
defer eventBroadcaster.Shutdown()
```
These are potential places for writes into closed channels.

File: pkg/descheduler/descheduler.go (hunk 4 above)
Comment (knelasevero) [reply pkg/descheduler/descheduler.go]: :heavy_check_mark:

**Comment by knelasevero** [comment]
> There are still few places in unit tests that have:
> 
> ```
> eventBroadcaster, eventRecorder := utils.GetRecorderAndBroadcaster(ctx, fakeClient)
> defer eventBroadcaster.Shutdown()
> ```
> 
> These are potential places for writes into closed channels.

I think I got all now. Just pushed :)

File: pkg/descheduler/strategies/duplicates_test.go [hunk 12]
```diff
@@ -751,6 +755,8 @@ func TestRemoveDuplicatesUniformly(t *testing.T) {
 			sharedInformerFactory.Start(ctx.Done())
 			sharedInformerFactory.WaitForCacheSync(ctx.Done())
 
+			eventRecorder := events.NewFakeRecorder(utils.FakeRecorderSize)
```
[the remark this answers is not in the document]
Comment (knelasevero) [reply pkg/descheduler/strategies/duplicates_test.go:758]: With lower sizes it was hanging forever and reaching timeouts. I had to keep increasing this size to get tests to pass

[the remark this answers is not in the document]
Comment (knelasevero) [reply pkg/descheduler/strategies/duplicates_test.go]: Went with &events.FakeRecorder{} :heavy_check_mark:

**Comment by ingvagabund** [comment]
/hold
to give some time to other reviewers to take a look
/lgtm
feel free to unhold after a day or two

**Comment by knelasevero** [comment]
> @knelasevero @ingvagabund it looks like there was a lot of iteration on this, is the main PR description still up to date with the changes? (or could we get a summary of your findings)

Basically I went with what we discussed here:  [comment](https://github.com/kubernetes-sigs/descheduler/pull/888/#discussion_r926863909)

- Started using new events implementation. 
- Mimicked some of what is being done in KS, so using different clientSet for **events** and for the actual **descheduler** actions. 
- Used &events.FakeRecorder{} in tests instead of the real thing.
- Instantiated the broadcaster and recorder only one time outside NonSlidingUntil


I think that's it. Sorry, I should have waited a bit more to squash the commits :)

**Review by JaneLiuL — COMMENTED** [review]
/lgtm
