### PR TITLE
RemovePodsViolatingTopologySpreadConstraint : Take node's taints into consideration when balancing domains

### LINKED ISSUE #566: RemovePodsViolatingTopologySpreadConstraint: endless loop of eviction/scheduling for tainted nodes
**What version of descheduler are you using?**

descheduler version: `v0.21.0` (built using latest SHA on master)

**Does this issue reproduce with the latest release?** Yes

**Which descheduler CLI options are you using?** None

**Please provide a copy of your descheduler policy config file**
```
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemovePodsViolatingTopologySpreadConstraint":
    enabled: true
```

**What k8s version are you using (`kubectl version`)?**

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-22T22:54:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"
</pre></details>

**What did you do?**
I created a Kind cluster with 2 workers nodes where one worker node is tainted (and therefore unschedulable).
Following that, I created 2 Deployments and both with a `topologySpreadConstraints` with key`topology.kubernetes.io/zone` (without any tolerations).
Given that neither deployment has a toleration specified, it can never be scheduled on the tainted node.
However, it seems that descheduler does not accommodate for that and causes an endless loop of eviction/scheduling.

**What did you expect to see?**
Pod to not get evicted given that there is no additional capacity available for scheduling.

**What did you see instead?**
Pod keeps getting evicted and rescheduled back on the only available worker node.

**Steps to reproduce locally**
1. Create a Kind cluster with 2 worker nodes
```
cat <<EOF | kind create cluster --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: descheduler
nodes:
- role: control-plane
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
- role: worker
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=local-a"
- role: worker
  image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "topology.kubernetes.io/zone=local-b"
      taints:
      - effect: NoSchedule
        key: "special"
        value: "true"
EOF
```
Creating cluster "descheduler" ...
 ✓ Ensuring node image (kindest/node:v1.19.7) 🖼
 ✓ Preparing nodes 📦 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Joining worker nodes 🚜
Set kubectl context to "kind-descheduler"
You can now use your cluster with:
kubectl cluster-info --context kind-descheduler
Have a nice day! 👋

2. Follow steps from descheduler README and run the following to run the Descheduler CronJob. _I modified this to reference the Docker image built using the latest verison_.
```
kubectl create -f kubernetes/base/rbac.yaml
kubectl create -f kubernetes/cronjob/cronjob.yaml
```

3. Don't use the default configmap, but instead use the one below.
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemovePodsViolatingTopologySpreadConstraint":
        enabled: true
        params:
          includeSoftConstraints: true
EOF
```

4. Create test namespace:
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Namespace
metadata:
  name: test
EOF
```

5. Create a Deployment with a topology constraint 
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: http
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app: nginx
EOF
```

6. Create a second deployment just like the one above but with a `nodeSelector` to make sure it is scheduled on the same zone (forthis example `nodeSelector` could be optional since there is only one schedulable node).
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: http
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: "ScheduleAnyway"
        labelSelector:
          matchLabels:
            app: nginx
      nodeSelector:
        topology.kubernetes.io/zone: local-a
EOF
```
7. Observe endless loops of eviction/scheduling:
```
 kubectl get pods -n test -owide -w
NAME                    READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
app-866755bcdc-s625p    1/1     Running   0          10s   10.244.1.6   descheduler-worker   <none>           <none>
app2-68d96c4dd9-czvw5   1/1     Running   0          10s   10.244.1.5   descheduler-worker   <none>           <none>
app-866755bcdc-s625p    1/1     Terminating   0          60s   10.244.1.6   descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    0/1     Pending       0          0s    <none>       descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    0/1     ContainerCreating   0          0s    <none>       descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    1/1     Running             0          1s    10.244.1.8   descheduler-worker   <none>           <none>
app-866755bcdc-s625p    0/1     Terminating         0          61s   10.244.1.6   descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    1/1     Terminating         0          60s   10.244.1.8   descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    0/1     Pending             0          0s    <none>       descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    0/1     ContainerCreating   0          0s    <none>       descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    0/1     Terminating         0          61s   10.244.1.8   descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    1/1     Running             0          1s    10.244.1.10   descheduler-worker   <none>           <none>
app-866755bcdc-hpb7c    0/1     Terminating         0          66s   10.244.1.8    descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    1/1     Terminating         0          60s   10.244.1.10   descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    0/1     Terminating         0          61s   10.244.1.10   descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    1/1     Running             0          1s    10.244.1.12   descheduler-worker   <none>           <none>
app-866755bcdc-hpww8    0/1     Terminating         0          62s   10.244.1.10   descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    1/1     Terminating         0          60s   10.244.1.12   descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    0/1     Terminating         0          62s   10.244.1.12   descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    1/1     Running             0          2s    10.244.1.14   descheduler-worker   <none>           <none>
app-866755bcdc-kgjt7    0/1     Terminating         0          66s   10.244.1.12   descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    1/1     Terminating         0          61s   10.244.1.14   descheduler-worker   <none>           <none>
app-866755bcdc-49kvt    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-49kvt    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    0/1     Terminating         0          62s   10.244.1.14   descheduler-worker   <none>           <none>
app-866755bcdc-49kvt    1/1     Running             0          1s    10.244.1.16   descheduler-worker   <none>           <none>
app-866755bcdc-lhtkr    0/1     Terminating         0          66s   10.244.1.14   descheduler-worker   <none>           <none>
app-866755bcdc-49kvt    1/1     Terminating         0          60s   10.244.1.16   descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    1/1     Running             0          1s    10.244.1.18   descheduler-worker   <none>           <none>
app-866755bcdc-49kvt    0/1     Terminating         0          65s   10.244.1.16   descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    1/1     Terminating         0          60s   10.244.1.18   descheduler-worker   <none>           <none>
app-866755bcdc-kgvld    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    0/1     Terminating         0          61s   10.244.1.18   descheduler-worker   <none>           <none>
app-866755bcdc-kgvld    1/1     Running             0          1s    10.244.1.20   descheduler-worker   <none>           <none>
app-866755bcdc-jzwx2    0/1     Terminating         0          65s   10.244.1.18   descheduler-worker   <none>           <none>
app-866755bcdc-kgvld    1/1     Terminating         0          60s   10.244.1.20   descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-kgvld    0/1     Terminating         0          61s   10.244.1.20   descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    1/1     Running             0          1s    10.244.1.22   descheduler-worker   <none>           <none>
app-866755bcdc-kgvld    0/1     Terminating         0          65s   10.244.1.20   descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    1/1     Terminating         0          60s   10.244.1.22   descheduler-worker   <none>           <none>
app-866755bcdc-vvjbj    0/1     Pending             0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-vvjbj    0/1     ContainerCreating   0          0s    <none>        descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    0/1     Terminating         0          60s   10.244.1.22   descheduler-worker   <none>           <none>
app-866755bcdc-njt6h    0/1     Terminating         0          61s   10.244.1.22   descheduler-worker   <none>           <none>
app-866755bcdc-vvjbj    1/1     Running             0          1s    10.244.1.24   descheduler-worker   <none>           <none>
...
```
Logs from multiple runs:
```
descheduler-cronjob-1620757320-zjv2m descheduler I0511 18:22:03.510147       1 topologyspreadconstraint.go:109] "Processing namespaces for topology spread constraints"
descheduler-cronjob-1620757320-zjv2m descheduler I0511 18:22:03.543353       1 evictions.go:123] "Evicted pod" pod="test/app-866755bcdc-s625p" reason="PodTopologySpread"
descheduler-cronjob-1620757320-zjv2m descheduler I0511 18:22:03.543770       1 descheduler.go:136] "Number of evicted pods" totalEvicted=1

descheduler-cronjob-1620757380-xjbtn descheduler I0511 18:23:03.871751       1 topologyspreadconstraint.go:109] "Processing namespaces for topology spread constraints"
descheduler-cronjob-1620757380-xjbtn descheduler I0511 18:23:03.908512       1 evictions.go:123] "Evicted pod" pod="test/app-866755bcdc-hpb7c" reason="PodTopologySpread"
descheduler-cronjob-1620757380-xjbtn descheduler I0511 18:23:03.914834       1 descheduler.go:136] "Number of evicted pods" totalEvicted=1

descheduler-cronjob-1620757440-plq27 descheduler I0511 18:24:03.811630       1 topologyspreadconstraint.go:109] "Processing namespaces for topology spread constraints"
descheduler-cronjob-1620757440-plq27 descheduler I0511 18:24:03.856065       1 evictions.go:123] "Evicted pod" pod="test/app-866755bcdc-hpww8" reason="PodTopologySpread"
descheduler-cronjob-1620757440-plq27 descheduler I0511 18:24:03.856492       1 descheduler.go:136] "Number of evicted pods" totalEvicted=1

uler-cronjob-1620758040-67nv5 descheduler I0511 18:34:04.586575       1 topologyspreadconstraint.go:109] "Processing namespaces for topology spread constraints"
descheduler-cronjob-1620758040-67nv5 descheduler I0511 18:34:04.623012       1 evictions.go:123] "Evicted pod" pod="test/app-866755bcdc-glr82" reason="PodTopologySpread"
descheduler-cronjob-1620758040-67nv5 descheduler I0511 18:34:04.623190       1 descheduler.go:136] "Number of evicted pods" totalEvicted=1
```

### PR DESCRIPTION
**Pull request by a7i**
If a pod does not tolerate a node's taints, then it should not be considered for eviction.

Fixes #566

### CODE REVIEW

File: pkg/descheduler/strategies/topologyspreadconstraint.go [hunk 1]
```diff
@@ -311,7 +317,21 @@ func balanceDomains(
...
-		if nodeutil.PodFitsCurrentNode(pod, node) && node != nodeMap[pod.Spec.NodeName] {
+		if node != nodeMap[pod.Spec.NodeName] && nodeutil.PodFitsCurrentNode(pod, node) {
+			count++
+		}
+	}
+	return count
+}
+
+// nodesPodToleratedOnBesidesCurrent counts the number of nodes this pod could fit on based on its toleration and the node's taints.
+func nodesPodToleratedOnBesidesCurrent(pod *v1.Pod, nodeMap map[string]*v1.Node) int {
```
Comment (damemi) [inline pkg/descheduler/strategies/topologyspreadconstraint.go:328]: does this need to be a new function or could it just be an additional check in `nodesPodFitsOnBesidesCurrent`?

**Review by damemi — COMMENTED** [review]
/ok-to-test
thanks @a7i for updating this

as a future todo, I'd like to refactor this strategy to consider these checks before adding pods to `aboveToEvict` (right now we just calculate the number of pods to move with `aboveToEvict := sortedDomains[j].pods[len(sortedDomains[j].pods)-movePods:]`, and if any of the pods in that slice don't fit they are simply ignored, hurting the efficiency of the strategy)

File: pkg/descheduler/strategies/topologyspreadconstraint.go (hunk 1 above)
Comment (a7i) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:328]: The intention was to have a more clear warning message for debugging purposes. `"Ignoring pod for eviction due to node taints not being tolerated"`
Happy to change if you suggest.

Comment (damemi) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:328]: Yeah, I think combining these is better than looping over the `nodeMap` twice. You could update `nodesPodFitsOnBesidesCurrent` to return an error about what check specifically failed

Comment (a7i) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:328]: Note that `nodesPodFitsOnBesidesCurrent` check only runs when there is a nodeSelector affinity condition required during scheduling.
This is not the case for taints.

Comment (damemi) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:328]: Ah, good point. Though, we could move that conditional inside the function and skip the selector/affinity check then. Wdyt?

Comment (a7i) [reply pkg/descheduler/strategies/topologyspreadconstraint.go]: I like it. Done, look forward to your feedback.

File: pkg/descheduler/strategies/topologyspreadconstraint.go [hunk 2]
```diff
@@ -283,39 +283,65 @@ func balanceDomains(
...
+			taintNotToleratedCount++
+			continue
 		}
+
+		availableTargetNodes++
+	}
+
+	if availableTargetNodes == 0 {
+		return fmt.Errorf(
+			"ignoring pod for eviction due to %d nodes with ineligible selector/affinity and %d nodes with taints that are not tolerated",
```
Comment (damemi) [inline pkg/descheduler/strategies/topologyspreadconstraint.go:339]: you could set the error specifically based on the above checks, so we know if it was either skipped due to affinity or taints. Perhaps even aggregate them in case it's both: https://pkg.go.dev/k8s.io/apimachinery/pkg/util/errors#NewAggregate

Comment (a7i) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:339]: note that it could be because of the combination of both:

let's say we have 6 target nodes:
3 nodes with ineligible nodeSelector/Affinity
3 nodes with taints

=> not evicted

Comment (damemi) [reply pkg/descheduler/strategies/topologyspreadconstraint.go:339]: Right, but it's an odd error to return, for example: `ignoring due to 0 nodes with selector and 6 nodes with affinity`

It would be more descriptive to list which nodes are failing for what, and don't include any unnecessary information. Using an aggretate error struct would be the easiest way to do that I think

File: pkg/descheduler/strategies/topologyspreadconstraint.go [hunk 3]
```diff
@@ -283,39 +284,68 @@ func balanceDomains(
...
+
+	if availableTargetNodes == 0 {
+		var errs []error
+		if ineligibleAffinityCount > 0 {
+			errs = append(errs, fmt.Errorf("ignoring pod for eviction due to %d nodes with ineligible selector/affinity", ineligibleAffinityCount))
+		}
+		if taintNotToleratedCount > 0 {
+			errs = append(errs, fmt.Errorf("ignoring pod for eviction due to %d nodes with taints that are not tolerated", taintNotToleratedCount))
 		}
+		return utilerrors.NewAggregate(errs)
```
Comment (damemi) [inline pkg/descheduler/strategies/topologyspreadconstraint.go:346]: Thanks, this looks a little better. Though, I more had in mind aggregating the errors within the node loop (but I wasn't clear about that, sorry).

But I like this direction. Instead of just incrementing a count, could you build a slice of the actual node names that don't match? Then change each of these errors to list the names, like:
```go
errs = append(errs, fmt.Errorf("%d nodes with ineligible selector/affinity: %+v", len(ineligibleAffinityNodes), ineligibleAffinityNodes))
```

and in the call to this function, prepend the error info there:
```go
klog.V(2).InfoS(fmt.Errorf("ignoring pod for eviction due to: %s", err.Error()), "pod", klog.KObj(aboveToEvict[k]))
```

Though, listing the actual node names might be a bit too much on large clusters. So I'm okay with not doing that, however I would like to remove the duplicate text. After that lgtm

**Review by damemi — COMMENTED** [review]
/lgtm
/approve
thanks @a7i !
