### PR TITLE
Fix Version Output For Automated Container Builds

### LINKED ISSUE #425: Descheduler Version Not Working in Official Container Images
**What version of descheduler are you using?**

descheduler version: v0.19.0

**Does this issue reproduce with the latest release?**
Yes.

**Which descheduler CLI options are you using?**
```
descheduler version
```

**Please provide a copy of your descheduler policy config file**
N/A

**What k8s version are you using (`kubectl version`)?**
v1.19.0

<details><summary><code>kubectl version</code> Output</summary><br><pre>
$ kubectl version

</pre></details>

**What did you do?**
I ran the below command. Note that the major and minor versions are empty.
```
docker run k8s.gcr.io/descheduler/descheduler:v0.19.0 /bin/descheduler version
Descheduler version {Major: Minor: GitCommit: GitVersion: BuildDate:2020-09-01T16:43:23+0000 GoVersion:go1.15 Compiler:gc Platform:linux/amd64}
```

**What did you expect to see?**
I expect `descheduler version` to output the correct version information when using the official container images from k8s.gcr.io.

**What did you see instead?**
The major and minor versions are empty.

### PR DESCRIPTION
**Pull request by seanmalloy**
Prior to this change the output from the command "descheduler version" when run using the official container images from k8s.gcr.io would always output an empty string. See below for an example.

```
docker run k8s.gcr.io/descheduler/descheduler:v0.19.0 /bin/descheduler version
Descheduler version {Major: Minor: GitCommit: GitVersion: BuildDate:2020-09-01T16:43:23+0000 GoVersion:go1.15 Compiler:gc Platform:linux/amd64}
```

This change makes it possible to pass the descheduler version information to the automated container image build process and also makes it work for local builds too.

Fixes #425

### CODE REVIEW

**Comment by seanmalloy** [comment]
Not quite done testing yet.

/hold

**Comment by seanmalloy** [comment]
Here is what the new output for `descheduler version` looks like after this change.

Example for local builds and automated builds using a commit(not a tag):
```
$ make build
CGO_ENABLED=0 go build -ldflags "-X sigs.k8s.io/descheduler/cmd/descheduler/app.version=v20201013-v0.18.0-181-g7ae3f9ea2 -X sigs.k8s.io/descheduler/cmd/descheduler/app.buildDate=2020-10-13T22:28:24-0500" -o _output/bin/descheduler sigs.k8s.io/descheduler/cmd/descheduler
$ ./_output/bin/descheduler version
Descheduler version {Major:0 Minor:18+ GitVersion:v20201013-v0.18.0-181-g7ae3f9ea2 BuildDate:2020-10-13T22:28:24-0500 GoVersion:go1.15.2 Compiler:gc Platform:darwin/amd64}
```

Example for automated builds using a tag:
```
$ VERSION=v20200521-v0.18.0 make build
CGO_ENABLED=0 go build -ldflags "-X sigs.k8s.io/descheduler/cmd/descheduler/app.version=v20200521-v0.18.0 -X sigs.k8s.io/descheduler/cmd/descheduler/app.buildDate=2020-10-13T22:35:46-0500" -o _output/bin/descheduler sigs.k8s.io/descheduler/cmd/descheduler
$ ./_output/bin/descheduler version
Descheduler version {Major:0 Minor:18+ GitVersion:v20200521-v0.18.0 BuildDate:2020-10-13T22:35:46-0500 GoVersion:go1.15.2 Compiler:gc Platform:darwin/amd64}
```

Example for automated builds using the helm chart tag. Yes, this is still broken:
```
$ VERSION=v20201012-descheduler-helm-chart-0.19.0-39-gb33928ac9 make build
CGO_ENABLED=0 go build -ldflags "-X sigs.k8s.io/descheduler/cmd/descheduler/app.version=v20201012-descheduler-helm-chart-0.19.0-39-gb33928ac9 -X sigs.k8s.io/descheduler/cmd/descheduler/app.buildDate=2020-10-13T22:37:09-0500" -o _output/bin/descheduler sigs.k8s.io/descheduler/cmd/descheduler
$ ./_output/bin/descheduler version
Descheduler version {Major: Minor: GitVersion:v20201012-descheduler-helm-chart-0.19.0-39-gb33928ac9 BuildDate:2020-10-13T22:37:09-0500 GoVersion:go1.15.2 Compiler:gc Platform:darwin/amd64}
```

**Comment by seanmalloy** [comment]
Also, tested the `make image` target.

```
$ make image
docker run descheduler:v20201014-v0.18.0-181-gcf020224a /bin/descheduler version
Descheduler version {Major:0 Minor:18+ GitVersion:v20201014-v0.18.0-181-gcf020224a BuildDate:2020-10-14T06:06:27+0000 GoVersion:go1.15.2 Compiler:gc Platform:linux/amd64}
```

and ...
```
$ VERSION=v20200521-v0.18.0 make image
$ docker run descheduler:v20200521-v0.18.0 /bin/descheduler version
Descheduler version {Major:0 Minor:18+ GitVersion:v20200521-v0.18.0 BuildDate:2020-10-14T06:11:35+0000 GoVersion:go1.15.2 Compiler:gc Platform:linux/amd64}
```

File: cmd/descheduler/app/version.go [hunk 1]
```diff
@@ -81,7 +77,19 @@ func splitVersion(version string) (string, string) {
...
+	// Version from an automated container build environment for a tag. For example v20200521-v0.18.0.
+	if matched, _ := regexp.MatchString(`^v\d{8}-v\d+\.\d+\.\d+$`, version); matched {
+		semVer := strings.Split(version, "-")[1]
+		return strings.Trim(strings.Split(semVer, ".")[0], "v"), strings.Split(semVer, ".")[1] + "+"
+	}
+
+	// Version from an automated container build environment(not a tag) or a local build. For example v20201009-v0.18.0-46-g939c1c0.
+	if matched, _ := regexp.MatchString(`^v\d{8}-v\d+\.\d+\.\d+-\w+-\w+$`, version); matched {
+		semVer := strings.Split(version, "-")[1]
+		return strings.Trim(strings.Split(semVer, ".")[0], "v"), strings.Split(semVer, ".")[1] + "+"
```
Comment (ingvagabund) [inline cmd/descheduler/app/version.go:90]: Any plans to parse the string differently? Right now both if blocks are identical.

Comment (seanmalloy) [reply cmd/descheduler/app/version.go:90]: Good catch. I'll take a look at this in a few days and refactor it to remove the duplicated code.

**Review by damemi — COMMENTED** [review]
@seanmalloy looks like you've got it working, but as you mentioned in https://github.com/kubernetes-sigs/descheduler/pull/427#issuecomment-708143044 this is obviously still going to print the wrong tag for automatic builds. So 2 questions: that shouldn't be a problem with images pulled from the published `v0.19.0` tags right? And also, would there be a way to parse the semver out of the `helm-chart` tag and use that?

File: cmd/descheduler/app/version.go (hunk 1 above)
Comment (seanmalloy) [reply cmd/descheduler/app/version.go:89]: I refactored in commit 4cc5dc9004b701172496ce4416967c939470c401. @ingvagabund let me know if you think this looks better or not. Thanks!

**Comment by seanmalloy** [comment]
@damemi see responses to your questions below.

> that shouldn't be a problem with images pulled from the published `v0.19.0` tags right?

Short answer, correct.

I believe once this PR is merged the `descheduler version` command will print the correct version information for the container images that are built for releases. I think the only gotcha when creating a release is that you must create and push the git tag prior to creating the release in the GitHub UI. Maybe someday there will be a shell script to automate the few manual release steps.

> And also, would there be a way to parse the semver out of the `helm-chart` tag and use that?

My concern would be that we would be putting in helm chart version into the descheduler binary instead of the descheduler version. Let me know if you disagree.

I don't have a great solution for this right now.

**Comment by damemi** [comment]
@seanmalloy cool, I actually think the recent updates we made to the chart releaser action might fix our automatic releases (the new version of the action tags from the branch it's created from, which will keep it separate from master see https://github.com/kubernetes-sigs/descheduler/pull/436#pullrequestreview-530183203).

> I think the only gotcha when creating a release is that you must create and push the git tag prior to creating the release in the GitHub UI.

Also btw, the tags can be created from the github UI when you create the release (this is how I've done the past couple releases 😉)

**Review by damemi — COMMENTED** [review]
@seanmalloy this looks good to me if you just squash the commits
/approve
/hold
@ingvagabund can lgtm (and remove the hold)

**Comment by seanmalloy** [comment]
I'll squash commits after @ingvagabund  reviews assuming there are not additional changes requested.

**Comment by ingvagabund** [comment]
Looks good, you can switch. I will lgtm right after. Thanks!!!

**Comment by seanmalloy** [comment]
@ingvagabund commits have been squashed.
