### PR TITLE
Rebase k8s dependencies to 1.19-rc.2

### LINKED ISSUE #353: Logging is broken with the switch to klog/v2
Testing a build with and without the changes in https://github.com/kubernetes-sigs/descheduler/pull/327, the switch to klog/v2 seems to have broken logging and nothing is printed, even at log level 5.

**What version of descheduler are you using?**
descheduler version: built from latest master

**Does this issue reproduce with the latest release?**
not 1.18, yes for 1.19

**Which descheduler CLI options are you using?**
```
        - --policy-config-file=/policy-dir/policy.yaml
        - --v=5
        - --descheduling-interval=3600s
```

**Please provide a copy of your descheduler policy config file**
```
  policy.yaml: |
    strategies:
      LowNodeUtilization:
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            numberOfNodes: 3
            targetThresholds:
              cpu: 10
              memory: 20
              pods: 30
            thresholds:
              cpu: 10
              memory: 20
              pods: 30
      RemoveDuplicates:
        enabled: true
```

**What k8s version are you using (`kubectl version`)?**
```
$ oc version
Client Version: v4.2.0-alpha.0-361-gcb858ac
Server Version: 4.6.0-0.nightly-2020-07-15-170241
Kubernetes Version: v1.18.3+7024740
```

/priority critical-urgent

### PR DESCRIPTION
**Pull request by damemi**
This is an in-place PR to start updating our deps to 1.19 for the upcoming 1.19 k8s release

Fixes #353

### CODE REVIEW

**Comment by damemi** [comment]
Weird that these checks are failing CI, they pass locally for me and I'm running go 1.14.4 (same as the [prow job image](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml#L16). Tested in a container:

```
$ docker run -it --rm -v $(pwd):/go/src/sigs.k8s.io/descheduler/.:Z golang:1.14.4 sh
# go version
go version go1.14.4 linux/amd64
# make verify
./hack/verify-gofmt.sh
./hack/verify-vendor.sh
go: downloading k8s.io/apimachinery v0.19.0-beta.2
go: downloading k8s.io/component-base v0.19.0-beta.2
go: downloading k8s.io/client-go v0.19.0-beta.2
go: downloading k8s.io/klog/v2 v2.1.0
go: downloading github.com/spf13/cobra v0.0.5
go: downloading k8s.io/apiserver v0.19.0-beta.2
go: downloading github.com/spf13/pflag v1.0.5
go: downloading k8s.io/code-generator v0.19.0-beta.2
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/google/gofuzz v1.1.0
go: downloading github.com/Azure/go-autorest/autorest v0.9.6
go: downloading k8s.io/api v0.19.0-beta.2
go: downloading sigs.k8s.io/yaml v1.2.0
go: downloading github.com/Azure/go-autorest/autorest/adal v0.8.2
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading golang.org/x/oauth2 v0.0.0-20191202225959-858c2ad4c8b6
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading k8s.io/utils v0.0.0-20200414100711-2df71ebbae66
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/evanphx/json-patch v4.2.0+incompatible
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/imdario/mergo v0.3.5
go: downloading k8s.io/gengo v0.0.0-20200428234225-8167cfdcfc14
go: downloading github.com/go-logr/logr v0.1.0
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/googleapis/gnostic v0.4.1
go: downloading sigs.k8s.io/structured-merge-diff/v3 v3.0.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/google/go-cmp v0.4.0
go: downloading github.com/golang/protobuf v1.4.2
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading google.golang.org/appengine v1.6.5
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading k8s.io/kube-openapi v0.0.0-20200427153329-656914f816f9
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/golang/groupcache v0.0.0-20191227052852-215e87163ea7
go: downloading github.com/Azure/go-autorest/tracing v0.5.0
go: downloading github.com/Azure/go-autorest/autorest/mocks v0.3.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
go: downloading golang.org/x/crypto v0.0.0-20200220183623-bac4c82f6975
go: downloading golang.org/x/tools v0.0.0-20191227053925-7b8e75db28f4
go: downloading github.com/google/uuid v1.1.1
go: downloading cloud.google.com/go v0.51.0
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading github.com/kr/pretty v0.2.0
go: downloading github.com/onsi/gomega v1.7.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/go-openapi/spec v0.19.3
go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading github.com/go-openapi/jsonreference v0.19.3
go: downloading github.com/Azure/go-autorest/logger v0.1.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/go-openapi/jsonpointer v0.19.3
go: downloading github.com/go-openapi/swag v0.19.5
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading github.com/mailru/easyjson v0.7.0
go: downloading github.com/kr/text v0.1.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/emicklei/go-restful v2.9.5+incompatible
go: downloading github.com/PuerkitoBio/purell v1.1.1
go: downloading github.com/PuerkitoBio/urlesc v0.0.0-20170810143723-de5bf2ad4578
Vendor Verified.
Removing ./hack/../_tmp/kube-vendor.3dNkBy
./_output/bin/golangci-lint run
./_output/bin/golangci-lint: 1: ./_output/bin/golangci-lint: ????: not found
./_output/bin/golangci-lint: 1: ./_output/bin/golangci-lint: Syntax error: "|" unexpected
make: *** [Makefile:88: lint] Error 2
# make test-unit
./test/run-unit-tests.sh
?   	sigs.k8s.io/descheduler/cmd/descheduler	[no test files]
?   	sigs.k8s.io/descheduler/cmd/descheduler/app	[no test files]
?   	sigs.k8s.io/descheduler/cmd/descheduler/app/options	[no test files]
?   	sigs.k8s.io/descheduler/pkg/api	[no test files]
?   	sigs.k8s.io/descheduler/pkg/api/v1alpha1	[no test files]
?   	sigs.k8s.io/descheduler/pkg/apis/componentconfig	[no test files]
?   	sigs.k8s.io/descheduler/pkg/apis/componentconfig/v1alpha1	[no test files]
ok  	sigs.k8s.io/descheduler/pkg/descheduler	0.506s
?   	sigs.k8s.io/descheduler/pkg/descheduler/client	[no test files]
ok  	sigs.k8s.io/descheduler/pkg/descheduler/evictions	0.078s
?   	sigs.k8s.io/descheduler/pkg/descheduler/evictions/utils	[no test files]
ok  	sigs.k8s.io/descheduler/pkg/descheduler/node	0.042s
ok  	sigs.k8s.io/descheduler/pkg/descheduler/pod	0.063s
?   	sigs.k8s.io/descheduler/pkg/descheduler/scheme	[no test files]
ok  	sigs.k8s.io/descheduler/pkg/descheduler/strategies	0.055s
?   	sigs.k8s.io/descheduler/pkg/utils	[no test files]
?   	sigs.k8s.io/descheduler/test	[no test files]
``` 

And I do get some error with golang ci but the vendor should verify and the tests should pass...

**Comment by damemi** [comment]
I think it's some assumption we're making in our script that's messed up... I can sometimes get it to reproduce the failure by switching to master and running verify-vendor, but then running update-vendor fixes it (and produces no noticeable code changes)

**Comment by damemi** [comment]
Ok I can consistently reproduce this by switching between `master` and my new branch `rebase-1.19`:

```
$ git checkout rebase-1.19 
Switched to branch 'rebase-1.19'

$ hack/verify-vendor.sh 
(fails with the weird non-diffs we see in CI)

$ hack/update-vendor.sh
(no changes)

$ hack/verify-vendor.sh 
Vendor Verified.
Removing hack/../_tmp/kube-vendor.1xgx7F

$ git checkout master
Switched to branch 'master'

$ hack/verify-vendor.sh 
(fails again)

$ hack/update-vendor.sh
(no diff)

$ hack/verify-vendor.sh 
Vendor Verified.
Removing hack/../_tmp/kube-vendor.XP4DV4
```

I can go back and forth with this pattern forever, but it seems like `hack/update-vendor.sh` specifically (which only calls `go mod tidy && go mod vendor`) makes some change that fixes verify-vendor, but is ignored by git

**Comment by damemi** [comment]
The problem is only related to OpenAPIV2 packages, related to the lowercasing of the new imports (see https://github.com/kubernetes/client-go/issues/741 and the linked kube-openapi PR in that issue). This would explain why the diff doesn't show up in git

`go mod vendor` keeps resetting the OpenAPIV2 package name to caps on an older branch:
```
mdame@ibm-p9b-04-bmc[rebase-1.19] ~/go/src/sigs.k8s.io/descheduler$ git checkout master
Switched to branch 'master'
mdame@ibm-p9b-04-bmc[master] ~/go/src/sigs.k8s.io/descheduler$ ls vendor/github.com/googleapis/gnostic/
total 12K
drwxr-xr-x 6 mdame staff 192 Jul  9 17:23 .
drwxr-xr-x 3 mdame staff  96 Jul  9 17:23 ..
drwxr-xr-x 9 mdame staff 288 Jul  9 17:26 compiler
drwxr-xr-x 7 mdame staff 224 Jul  9 17:26 extensions
drwxr-xr-x 7 mdame staff 224 Jul  9 17:26 openapiv2
-rw-r--r-- 1 mdame staff 12K Jul  9 17:23 LICENSE
mdame@ibm-p9b-04-bmc[master] ~/go/src/sigs.k8s.io/descheduler$ hack/update-vendor.sh 
mdame@ibm-p9b-04-bmc[master] ~/go/src/sigs.k8s.io/descheduler$ ls vendor/github.com/googleapis/gnostic/
total 12K
drwxr-xr-x 6 mdame staff 192 Jul  9 17:26 .
drwxr-xr-x 3 mdame staff  96 Jul  9 17:26 ..
drwxr-xr-x 7 mdame staff 224 Jul  9 17:26 OpenAPIv2
drwxr-xr-x 9 mdame staff 288 Jul  9 17:26 compiler
drwxr-xr-x 7 mdame staff 224 Jul  9 17:26 extensions
-rw-r--r-- 1 mdame staff 12K Jul  9 17:26 LICENSE
```
which carries over when switching to the newer branch, so that's why I could switch between them and reproduce the issue. The `rebase-1.19` (this) branch bumps the openapiv2 dependency to its new lowercase form. However, since git doesn't see the case change, it doesn't get committed and that's why it fails CI. Silly

**Comment by damemi** [comment]
Need to make changes to update our policy conversion since default conversions no longer take place in 1.19 after https://github.com/kubernetes/kubernetes/pull/90018

**Comment by damemi** [comment]
@seanmalloy @ingvagabund I just updated this PR to 1.19-rc2. If we want to merge this to get our master branch up to a "pre-release" state I'm ok with it, that will let us make sure our other ongoing changes right now will work with 1.19 and lets us update our CI as well. Then the eventual bump to GA 1.19 should just be smooth. What do you think?

File: pkg/api/register.go [hunk 1]
```diff
@@ -35,12 +33,6 @@ const GroupName = "descheduler"
 // SchemeGroupVersion is group version used to register these objects
 var SchemeGroupVersion = schema.GroupVersion{Group: GroupName, Version: runtime.APIVersionInternal}
 
-func init() {
-	if err := addKnownTypes(scheme.Scheme); err != nil {
```
Comment (seanmalloy) [inline pkg/api/register.go:39]: It looks like the `addKnownTypes` function(lines 46 to 51) is no longer called. So should the `addKnownTypes` function just be removed from this file too?

I also noticed that some other files have their own `addKnownTypes` functions, so maybe these should be cleaned up too?
* https://github.com/kubernetes-sigs/descheduler/blob/4014ebad9230f493bcafbdf95aa1c6749a432347/pkg/apis/componentconfig/register.go#L38
* pkg/apis/componentconfig/v1alpha1/register.go
* https://github.com/kubernetes-sigs/descheduler/blob/4014ebad9230f493bcafbdf95aa1c6749a432347/pkg/apis/componentconfig/v1alpha1/register.go#L51

I'm honestly not sure if these need to be cleaned up or not, but just wanted to point this out just in case.

**Comment by ingvagabund** [comment]
> @seanmalloy @ingvagabund I just updated this PR to 1.19-rc2. If we want to merge this to get our master branch up to a "pre-release" state I'm ok with it, that will let us make sure our other ongoing changes right now will work with 1.19 and lets us update our CI as well. Then the eventual bump to GA 1.19 should just be smooth. What do you think?

Sounds good. As long as release-1.19 branch is cut after GA 1.19 rebase.

**Comment by damemi** [comment]
> Sounds good. As long as release-1.19 branch is cut after GA 1.19 rebase.

Yeah that would be exactly the plan, to **not** cut release-1.19 until **after** 1.19 GA

File: pkg/api/register.go (hunk 1 above)
Comment (damemi) [reply pkg/api/register.go:39]: Good point, let me check these out. I think at least some of them can be removed if not all

Comment (damemi) [reply pkg/api/register.go:39]: This `addKnownTypes` is still used by the `SchemeBuilder`: https://github.com/kubernetes-sigs/descheduler/pull/337/commits/72946602bbc51c3aee3fe438120040a04e53cbdb#diff-f0456cede4d61f48e51015136685ba1dR25

The others in ComponentConfig aren't called, but I think I need to update those to manually invoke `AddToScheme` like I did here

**Comment by seanmalloy** [comment]
/lgtm
/hold

@damemi these changes look good tome. Please remove the hold when you are ready for this to merge.

**Comment by ingvagabund** [comment]
> Change gnostic/openapiv2 to lowercase in git

This will be troublesome every time someone runs `go mod ...`. Hopefully, it will get fixed upstream soon.

/lgtm

**Comment by damemi** [comment]
> > Change gnostic/openapiv2 to lowercase in git
> 
> This will be troublesome every time someone runs `go mod ...`. Hopefully, it will get fixed upstream soon.
> 
> /lgtm

This shouldn't be a problem once it's fixed here. It's really only a problem for case-insensitive filesystems (like Mac) which don't see the filename change when the version was bumped (and so, don't commit the change).

For that same reason, if anyone else is on a Mac they shouldn't see any change running go.mod, so nothing to worry about there. Just a hitch but from this version on it should be good

**Comment by damemi** [comment]
CI looks good, so I'll release the hold. Planned 1.19 GA is August 25, so this will give us some good soak time to catch any bugs (like #353, which this fixes so that's another reason to get it in sooner).

Thanks @seanmalloy and @ingvagabund 
/hold cancel
